name: Post my profile

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@v1.0.5
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Japanese Fonts
      run: |
        sudo apt install -y fonts-ipafont
        fc-cache -fv
        fc-list | grep -i ipa
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Start XVFB
      run: Xvfb :1000 &
    - name: Run post_profile
      run: | 
        pipenv run post_profile
        cat ./screenshot.base64 | base64 -d > profile.jpg
      env:
        DISPLAY: :1000
    - name: Archive Screenshots
      uses: actions/upload-artifact@v2
      with:
        path: profile.jpg
