name: Post my profile

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - uses: nanasess/setup-chromedriver@v1.0.5
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Run post_profile
      run: | 
        pipenv run post_profile
        cat ./screenshot.base64 | base64 -d > profile.jpg
      env:
        DISPLAY: :1000
    - name: Archive Screenshots
      uses: actions/upload-artifact@v2
      with:
        path: profile.jpg
